# PyKrx 네이버/거래소에서 스크래핑

In [1]:
pip install pykrx

Requirement already satisfied: pykrx in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (1.0.17)Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from pykrx) (1.21.0)
Requirement already satisfied: deprecated in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from pykrx) (1.2.12)
Requirement already satisfied: pandas in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from pykrx) (1.3.0)
Requirement already satisfied: requests in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from pykrx) (2.26.0)
Requirement already satisfied: datetime in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from pykrx) (4.3)
Requirement already satisfied: xlrd in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from pykrx) (2.0.1)

Requirement already satisfied: zope.interface in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from datetime->pykrx) (5.4.0)
Requirement already satisfied: pytz in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from datetime->pykrx) (2021.1)
Requirement already satisfied: wrapt<2,>=1.10 in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from deprecated->pykrx) (1.12.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from pandas->pykrx) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.7.3->pandas->pykrx) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from requests->pykrx) (2021.5.30)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from requests->pykrx) (2.0.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from requests->pykrx) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from requests->pykrx) (1.26.6)
Requirement already satisfied: setuptools in c:\users\jyb\appdata\local\programs\python\python39\lib\site-packages (from zope.interface->datetime->pykrx) (56.0.0)

In [74]:
# Stock 모듈

# MarketData API :  코스피 종목의 주가 관련 정보를 얻는 API
# get_market_ticker_list 메서드는 지정한 일자(YYYYMMDD)의 코스피 시장에 상장된 ticker를 리스트로 반환
# 날짜를 지정하지 않으면 내부적으로 최근 영업일을 계산해서 ticker 반환
from pykrx import stock
tickers = stock.get_market_ticker_list("20210701")
print(tickers)

['095570', '006840', '027410', '282330', '138930', '001460', '001465', '001040', '079160', '00104K', '000120', '011150', '011155', '001045', '097950', '097955', '000590', '012030', '016610', '005830', '000990', '000995', '139130', '001530', '000210', '001880', '000215', '375500', '37550K', '004840', '155660', '069730', '017940', '365550', '383220', '007700', '114090', '078930', '006360', '001250', '007070', '078935', '012630', '039570', '089470', '294870', '011200', '082740', '003560', '175330', '234080', '001060', '001067', '001065', '096760', '105560', '002380', '009070', '009440', '119650', '092220', '016380', '016385', '001390', '033180', '001940', '025000', '092230', '000040', '044450', '030200', '033780', '030210', '058850', '058860', '093050', '003550', '034220', '001120', '051900', '051905', '003555', '032640', '011070', '066570', '066575', '108670', '108675', '037560', '051910', '051915', '079550', '006260', '010120', '000680', '229640', '383800', '38380K', '023150', '035420', '181710', '005940', '005945', '338100', '034310', '008260', '004250', '004255', '010060', '005490', '010950', '010955', '034120', '101060', '005090', '001380', '004060', '002360', '009160', '123700', '025530', '034730', '011790', '018670', '001740', '001745', '006120', '006125', '210980', '068400', '302440', '326030', '361610', '03473K', '096770', '096775', '001510', '001515', '285130', '28513K', '017670', '000660', '064960', '100840', '003570', '036530', '005610', '011810', '077970', '071970', '002820', '084870', '002710', '002900', '024070', '037270', '000500', '000860', '035250', '011420', '002100', '009450', '267290', '012320', '000050', '214390', '012610', '009140', '013580', '012200', '012205', '002140', '010130', '002240', '009290', '017040', '017900', '037710', '030610', '339770', '007690', '005320', '001140', '002720', '083420', '014530', '014280', '014285', '008870', '001570', '002990', '002995', '011780', '011785', '214330', '001210', '073240', '092440', '000270', '024110', '013700', '004540', '004545', '001260', '008350', '008355', '004270', '003920', '003925', '025860', '005720', '005725', '002350', '002355', '003580', '251270', '090350', '090355', '000320', '000325', '006280', '005250', '005257', '004370', '072710', '058730', '023590', '019680', '019685', '006370', '008060', '00806K', '353200', '35320K', '000490', '008110', '005750', '006570', '001680', '001685', '084690', '084695', '128820', '117580', '016710', '003540', '003547', '003545', '009190', '014160', '047040', '009320', '042660', '003090', '069620', '000430', '006340', '006345', '003220', '024890', '002880', '000300', '012800', '015230', '001070', '006650', '001440', '084010', '001790', '001795', '001130', '003490', '003495', '005880', '003830', '016090', '069460', '192080', '012510', '004830', '004835', '024900', '145720', '002150', '001230', '023450', '004140', '007590', '005960', '005965', '026960', '002210', '102260', '000640', '170900', '028100', '282690', '001520', '001527', '001529', '084670', '082640', '001525', '008970', '092780', '049770', '018500', '006040', '030720', '014820', '014825', '163560', '004890', '002690', '000020', '000150', '000157', '241560', '000155', '042670', '034020', '336260', '33626K', '33626L', '016740', '192650', '024090', '003160', '092200', '013570', '210540', '007340', '026890', '115390', '032350', '330590', '000400', '023530', '004000', '286940', '280360', '004990', '00499K', '005300', '005305', '011170', '002270', '071840', '027740', '204320', '001080', '088980', '094800', '138040', '008560', '000060', '090370', '017180', '009900', '012690', '005360', '204210', '009680', '009580', '009200', '033920', '008420', '025560', '007120', '357250', '085620', '006800', '00680K', '006805', '002840', '268280', '107590', '134380', '003650', '155900', '003610', '001340', '035150', '002410', '096300', '007210', '002760', '003850', '000890', '003000', '001270', '001275', '026940', '015350', '011390', '005030', '002070', '100220', '030790', '005180', '003960', '008040', '007160', '014710', '006090', '001470', '006400', '006405', '006660', '028260', '02826K', '207940', '032830', '018260', '028050', '009150', '009155', '005930', '005935', '001360', '010140', '010145', '016360', '068290', '029780', '000810', '000815', '006110', '145990', '145995', '003230', '002170', '272550', '000070', '000075', '002810', '005680', '003720', '023000', '004380', '002450', '004440', '000520', '009770', '005500', '004690', '010960', '004450', '009470', '011230', '001820', '000390', '001290', '041650', '075180', '007540', '248170', '007860', '200880', '017390', '004410', '004415', '021050', '008490', '007610', '136490', '014910', '014915', '003080', '004980', '004985', '011300', '000180', '002420', '004360', '004365', '004490', '001430', '306200', '003030', '019440', '058650', '013000', '091090', '021820', '067830', '033530', '075580', '027970', '145210', '308170', '012600', '068270', '336370', '33637K', '33637L', '248070', '004430', '017550', '053210', '134790', '016590', '029530', '004970', '011930', '005390', '004170', '035510', '034300', '031430', '031440', '006880', '005800', '001720', '001725', '009270', '009275', '002700', '019170', '019175', '002870', '293940', '055550', '001770', '004080', '102280', '003410', '003620', '004770', '015540', '004920', '112610', '008700', '002790', '00279K', '002795', '090430', '090435', '002030', '183190', '002310', '012170', '267850', '020560', '122900', '010780', '001780', '018250', '161000', '011090', '005850', '012750', '023960', '298690', '140910', '078520', '015260', '007460', '003060', '244920', '036570', '138250', '380440', '085310', '009810', '900140', '014440', '111770', '009970', '003520', '000670', '006740', '012280', '012160', '015360', '007310', '002630', '271560', '001800', '070960', '316140', '033660', '118000', '010050', '006980', '017370', '105840', '010400', '049800', '016880', '095720', '005820', '010600', '008600', '033270', '014830', '000910', '047400', '011330', '077500', '002920', '000700', '003470', '003475', '011690', '072130', '000220', '000225', '000227', '001200', '000100', '000105', '003460', '003465', '008730', '008250', '025820', '214320', '088260', '139480', '007660', '005950', '015020', '093230', '074610', '102460', '084680', '350520', '334890', '000760', '014990', '101140', '006490', '023800', '034590', '129260', '023810', '249420', '000230', '013360', '003120', '003200', '007110', '007570', '007575', '008500', '081000', '020760', '020150', '103590', '015860', '226320', '317400', '033240', '000950', '348950', '194370', '025620', '036420', '030000', '271980', '001560', '002620', '006220', '089590', '004910', '004700', '001550', '000480', '120030', '018470', '002600', '185750', '063160', '001630', '044380', '013890', '013870', '071320', '010580', '035000', '088790', '003780', '010640', '100250', '051630', '272450', '011000', '002780', '002787', '002785', '009310', '000650', '033250', '035720', '006380', '109070', '001620', '029460', '344820', '281820', '145270', '357120', '007815', '007810', '00781K', '003690', '192820', '044820', '005070', '005420', '071950', '002020', '003070', '003075', '144620', '002025', '120110', '120115', '138490', '021240', '031820', '192400', '284740', '015590', '264900', '26490K', '005740', '005745', '020120', '039490', '014580', '015890', '006890', '003240', '011280', '004100', '004105', '009410', '009415', '001420', '007980', '055490', '078000', '214420', '019180', '363280', '36328K', '091810', '004870', '005690', '036580', '004720', '028670', '010820', '016800', '001020', '090080', '010770', '058430', '047050', '003670', '007630', '017810', '103140', '005810', '950210', '086790', '293480', '039130', '172580', '153360', '352820', '071090', '019490', '000080', '000087', '000140', '000145', '152550', '036460', '005430', '071050', '071055', '010040', '025540', '004090', '002200', '002960', '000240', '123890', '015760', '006200', '009540', '023350', '025890', '000970', '104700', '017960', '161890', '024720', '161390', '034830', '007280', '168490', '010100', '047810', '123690', '003350', '011500', '002390', '014790', '060980', '053690', '042700', '008930', '128940', '009240', '020000', '003680', '105630', '069640', '016450', '010420', '009180', '213500', '014680', '004710', '004150', '025750', '004960', '011700', '001750', '001755', '018880', '009420', '014130', '300720', '002220', '006390', '003300', '051600', '052690', '130660', '002320', '097230', '003480', '180640', '18064K', '005110', '009460', '000880', '00088K', '088350', '000370', '009830', '009835', '272210', '012450', '000885', '003530', '003535', '195870', '101530', '143210', '000720', '267270', '000725', '005440', '086280', '064350', '079430', '012330', '010620', '069960', '004560', '004565', '004310', '322000', '017800', '307950', '011210', '267260', '004020', '267250', '005380', '005387', '005389', '005385', '001500', '011760', '227840', '126560', '001450', '057050', '093240', '003010', '111110', '008770', '008775', '002460', '378850', '241590', '006060', '013520', '010690', '133820', '010660', '000850', '016580', '032560', '004800', '094280', '298040', '298050', '298020', '298000', '093370', '081660', '005870', '079980', '005010', '069260', '000540', '000547', '000545', '003280']

In [ ]:
# market 옵션을 추가하면 조회 시장을 지정 가능
# KOSPI, KOSDAQ, KONEX 시장을 지정

tickers = stock.get_market_ticker_list("20210701", market="KOSDAQ")
print(tickers)

In [64]:
for ticker in stock.get_market_ticker_list():
        종목 = stock.get_market_ticker_name(ticker)
        print(종목)

AJ네트웍스
AK홀딩스
BGF
BGF리테일
BNK금융지주
BYC
BYC우
CJ
CJ CGV
CJ4우(전환)
CJ대한통운
CJ씨푸드
CJ씨푸드1우
CJ우
CJ제일제당
CJ제일제당 우
CS홀딩스
DB
DB금융투자
DB손해보험
DB하이텍
DB하이텍1우
DGB금융지주
DI동일
DL
DL건설
DL우
DL이앤씨
DL이앤씨우
DRB동일
DSR
DSR제강
E1
ESR켄달스퀘어리츠
F&F
F&F홀딩스
GKL
GS
GS건설
GS글로벌
GS리테일
GS우
HDC
HDC아이콘트롤스
HDC현대EP
HDC현대산업개발
HMM
HSD엔진
IHQ
JB금융지주
JW생명과학
JW중외제약
JW중외제약2우B
JW중외제약우
JW홀딩스
KB금융
KCC
KCC글라스
KCTC
KC그린홀딩스
KC코트렐
KEC
KG동부제철
KG동부제철우
KG케미칼
KH 필룩스
KISCO홀딩스
KPX케미칼
KPX홀딩스
KR모터스
KSS해운
KT
KT&G
KTB투자증권
KTcs
KTis
LF
LG
LG디스플레이
LG생활건강
LG생활건강우
LG우
LG유플러스
LG이노텍
LG전자
LG전자우
LG헬로비전
LG화학
LG화학우
LIG넥스원
LS
LS ELECTRIC
LS네트웍스
LS전선아시아
LX인터내셔널
LX하우시스
LX하우시스우
LX홀딩스
LX홀딩스1우
MH에탄올
NAVER
NHN
NH투자증권
NH투자증권우
NH프라임리츠
NICE
NI스틸
NPC
NPC우
OCI
POSCO
S-Oil
S-Oil우
SBS
SBS미디어홀딩스
SGC에너지
SG글로벌
SG세계물산
SH에너지화학
SIMPAC
SJM
SJM홀딩스
SK
SKC
SK가스
SK네트웍스
SK네트웍스우
SK디스커버리
SK디스커버리우
SK디앤디
SK렌터카
SK바이오사이언스
SK바이오팜
SK아이이테크놀로지
SK우
SK이노베이션
SK이노베이션우
SK증권
SK증권우
SK케미칼
SK케미칼우
SK텔레콤
SK하이닉스
SNT모티브
SNT에너지
SNT중공업
SNT홀딩스
SPC삼립
STX
STX엔진
STX중공업
SUN&L
TBH글로벌
TCC스틸
TYM
WISCOM
YG PLUS
가온전선
강남제비스코
강원랜드
갤럭시아에스엠
경농
경동나비엔
경동도시가스
경동인베스트
경방
경보제약
경인양행
경인전자
계룡건설
계양전기
계양전기우
고려산업
고려아연
고려제강
광동제약
광명전기
광전자
광주신세계
교보증권
교촌에프앤비
국도화학
국동
국보
국제약품
그린케미칼
극동유화
금강공업
금강공업우
금비
금양
금호건설
금호건설우
금호석유
금호석유우
금호에이치티
금호전기
금호타이어
기신정기
기아
기업은행
까뮤이앤씨
깨끗한나라
깨끗한나라우
남광토건
남선알미늄
남선알미우
남성
남양유업
남양유업우
남해화학
넥센
넥센우
넥센타이어
넥센타이어1우B
넥스트사이언스
넷마블
노루페인트
노루페인트우
노루홀딩스
노루홀딩스우
녹십자
녹십자홀딩스
녹십자홀딩스2우
농심
농심홀딩스
다스코
다우기술
대교
대교우B
대구백화점
대덕
대덕1우
대덕전자
대덕전자1우
대동
대동전자
대림B&Co
대림통상
대상
대상우
대상홀딩스
대상홀딩스우
대성산업
대성에너지
대성홀딩스
대신증권
대신증권2우B
대신증권우
대양금속
대영포장
대우건설
대우부품
대우조선해양
대웅
대웅제약
대원강업
대원전선
대원전선우
대원제약
대원화성
대유에이텍
대유플러스
대창
대창단조
대한방직
대한유화
대한전선
대한제강
대한제당
대한제당우
대한제분
대한항공
대한항공우
대한해운
대한화섬
대현
대호에이엘
더블유게임즈
더존비즈온
덕성
덕성우
덕양산업
덴티움
도화엔지니어링
동국제강
동남합성
동방
동방아그로
동부건설
동부건설우
동서
동성제약
동성케미컬
동아쏘시오홀딩스
동아에스티
동아지질
동아타이어
동양
동양2우B
동양3우B
동양고속
동양생명
동양우
동양철관
동양피스톤
동원F&B
동원금속
동원산업
동원수산
동원시스템즈
동원시스템즈우
동일고무벨트
동일산업
동일제강
동화약품
두산
두산2우B
두산밥캣
두산우
두산인프라코어
두산중공업
두산퓨얼셀
두산퓨얼셀1우
두산퓨얼셀2우B
두올
드림텍
디씨엠
디아이
디아이씨
디와이
디와이파워
디티알오토모티브
디피씨
락앤락
롯데관광개발
롯데리츠
롯데손해보험
롯데쇼핑
롯데정밀화학
롯데정보통신
롯데제과
롯데지주
롯데지주우
롯데칠성
롯데칠성우
롯데케미칼
롯데푸드
롯데하이마트
마니커
만도
만호제강
맥쿼리인프라
맵스리얼티1
메리츠금융지주
메리츠증권
메리츠화재
메타랩스
명문제약
명신산업
모나리자
모나미
모두투어리츠
모토닉
무림P&P
무림페이퍼
무학
문배철강
미래산업
미래아이앤지
미래에셋맵스리츠
미래에셋생명
미래에셋증권
미래에셋증권2우B
미래에셋증권우
미원상사
미원에스씨
미원홀딩스
미원화학
미창석유
바다로19호
방림
백광산업
백산
범양건영
베트남개발1
벽산
보락
보령제약
보해양조
부광약품
부국증권
부국증권우
부국철강
부산가스
부산산업
부산주공
비비안
비상교육
비케이탑스
빙그레
사조대림
사조동아원
사조산업
사조씨푸드
사조오양
삼부토건
삼성SDI
삼성SDI우
삼성공조
삼성물산
삼성물산우B
삼성바이오로직스
삼성생명
삼성에스디에스
삼성엔지니어링
삼성전기
삼성전기우
삼성전자
삼성전자우
삼성제약
삼성중공업
삼성중공우
삼성증권
삼성출판사
삼성카드
삼성화재
삼성화재우
삼아알미늄
삼양사
삼양사우
삼양식품
삼양통상
삼양패키징
삼양홀딩스
삼양홀딩스우
삼영무역
삼영전자
삼영화학
삼원강재
삼익THK
삼익악기
삼일씨엔에스
삼일제약
삼정펄프
삼진제약
삼천리
삼호개발
삼화왕관
삼화전기
삼화전자
삼화콘덴서
삼화페인트
상상인증권
상신브레이크
새론오토모티브
샘표
샘표식품
서연
서연이화
서울가스
서울식품
서울식품우
서원
서흥
선도전기
선진
성문전자
성문전자우
성보화학
성신양회
성신양회우
성안
성창기업지주
세기상사
세방
세방우
세방전지
세아베스틸
세아제강
세아제강지주
세아특수강
세아홀딩스
세우글로벌
세원이앤씨
세원정공
세이브존I&C
세종공업
세진중공업
세하
세화아이엠씨
센트랄모텍
센트럴인사이트
셀트리온
솔루스첨단소재
솔루스첨단소재1우
솔루스첨단소재2우B
솔루엠
송원산업
수산중공업
스카이라이프
시디즈
신대양제지
신도리코
신라교역
신성이엔지
신성통상
신세계
신세계 I&C
신세계건설
신세계인터내셔날
신세계푸드
신송홀딩스
신영와코루
신영증권
신영증권우
신원
신원우
신일전자
신풍제약
신풍제약우
신풍제지
신한알파리츠
신한지주
신화실업
신흥
쌍방울
쌍용C&E
쌍용차
써니전자
쎌마테라퓨틱스
씨아이테크
씨에스윈드
아남전자
아모레G
아모레G3우(전환)
아모레G우
아모레퍼시픽
아모레퍼시픽우
아세아
아세아시멘트
아세아제지
아센디오
아시아나IDT
아시아나항공
아이마켓코리아
아이에스동서
알루코
애경산업
애경유화
에넥스
에스디바이오센서
에스엘
에스원
에쓰씨엔지니어링
에어부산
에이리츠
에이블씨엔씨
에이엔피
에이프로젠 MED
에이프로젠제약
에이플러스에셋
엔씨소프트
엔에스쇼핑
엔에이치스팩19호
엔케이
엔케이물산
엘브이엠씨홀딩스
엠씨넥스
영보화학
영원무역
영원무역홀딩스
영진약품
영풍
영풍제지
영화금속
영흥
예스코홀딩스
오뚜기
오리엔트바이오
오리온
오리온홀딩스
용평리조트
우리금융지주
우리금융캐피탈
우리들휴브레인
우리종금
우성사료
우신시스템
우진
우진아이엔에스
우진플라임
웅진
웅진씽크빅
원림
웰바이오텍
윌비스
유나이티드제약
유니드
유니온
유니온머티리얼
유니켐
유니퀘스트
유성기업
유수홀딩스
유안타증권
유안타증권우
유양디앤유
유엔젤
유유제약
유유제약1우
유유제약2우B
유진투자증권
유한양행
유한양행우
유화증권
유화증권우
율촌화학
이건산업
이구산업
이노션
이리츠코크렙
이마트
이수페타시스
이수화학
이스타코
이아이디
이엔플러스
이연제약
이월드
이지스레지던스리츠
이지스밸류리츠
이화산업
인디에프
인바이오젠
인스코비
인지컨트롤스
인천도시가스
인터지스
인팩
일동제약
일동홀딩스
일성건설
일성신약
일신방직
일신석재
일양약품
일양약품우
일정실업
일진다이아
일진디스플
일진머티리얼즈
일진전기
일진홀딩스
잇츠한불
자이에스앤디
자화전자
전방
제이알글로벌리츠
제이에스코퍼레이션
제이준코스메틱
제이콘텐트리
제일기획
제일약품
제일연마
제일파마홀딩스
제주은행
제주항공
조광페인트
조광피혁
조비
조선내화
조선선재
조일알미늄
조흥
종근당
종근당바이오
종근당홀딩스
주연테크
지누스
지엠비코리아
지역난방공사
지코
지투알
진도
진양산업
진양폴리
진양홀딩스
진양화학
진에어
진원생명과학
진흥기업
진흥기업2우B
진흥기업우B
참엔지니어링
천일고속
체시스
카카오
카프로
컨버즈
케이비아이동국실업
케이씨
케이씨텍
케이탑리츠
코람코에너지리츠
코리아써우
코리아써키트
코리아써키트2우B
코리안리
코스맥스
코스맥스비티아이
코스모신소재
코스모화학
코아스
코오롱
코오롱글로벌
코오롱글로벌우
코오롱머티리얼
코오롱우
코오롱인더
코오롱인더우
코오롱플라스틱
코웨이
콤텍시스템
쿠쿠홀딩스
쿠쿠홈시스
큐로
크라운제과
크라운제과우
크라운해태홀딩스
크라운해태홀딩스우
키다리스튜디오
키움증권
태경비케이
태경산업
태경케미컬
태광산업
태림포장
태양금속
태양금속우
태영건설
태영건설우
태원물산
태평양물산
테이팩스
텔코웨어
토니모리
티에이치엔
티와이홀딩스
티와이홀딩스우
티웨이항공
티웨이홀딩스
파미셀
팜스코
팜젠사이언스
팬오션
퍼스텍
퍼시스
페이퍼코리아
평화산업
평화홀딩스
포스코강판
포스코인터내셔널
포스코케미칼
폴루스바이오팜
풀무원
풍산
풍산홀딩스
프레스티지바이오파마
하나금융지주
하나제약
하나투어
하이골드12호
하이골드3호
하이브
하이스틸
하이트론
하이트진로
하이트진로2우B
하이트진로홀딩스
하이트진로홀딩스우
한국ANKOR유전
한국가스공사
한국공항
한국금융지주
한국금융지주우
한국내화
한국단자
한국석유
한국수출포장
한국쉘석유
한국앤컴퍼니
한국자산신탁
한국전력
한국전자홀딩스
한국조선해양
한국종합기술
한국주강
한국주철관
한국철강
한국카본
한국콜마
한국콜마홀딩스
한국타이어앤테크놀로지
한국토지신탁
한국특강
한국패러랠
한국프랜지
한국항공우주
한국화장품
한국화장품제조
한농화성
한독
한라
한라홀딩스
한미글로벌
한미반도체
한미사이언스
한미약품
한샘
한섬
한성기업
한세실업
한세엠케이
한세예스24홀딩스
한솔PNS
한솔로지스틱스
한솔제지
한솔케미칼
한솔테크닉스
한솔홀딩스
한솔홈데코
한신공영
한신기계
한양증권
한양증권우
한온시스템
한올바이오파마
한익스프레스
한일시멘트
한일철강
한일현대시멘트
한일홀딩스
한전KPS
한전기술
한전산업
한진
한진중공업
한진중공업홀딩스
한진칼
한진칼우
한창
한창제지
한화
한화3우B
한화생명
한화손해보험
한화솔루션
한화솔루션우
한화시스템
한화에어로스페이스
한화우
한화투자증권
한화투자증권우
해성디에스
해태제과식품
핸즈코퍼레이션
현대건설
현대건설기계
현대건설우
현대그린푸드
현대글로비스
현대로템
현대리바트
현대모비스
현대미포조선
현대백화점
현대비앤지스틸
현대비앤지스틸우
현대약품
현대에너지솔루션
현대엘리베이
현대오토에버
현대위아
현대일렉트릭
현대제철
현대중공업지주
현대차
현대차2우B
현대차3우B
현대차우
현대차증권
현대코퍼레이션
현대코퍼레이션홀딩스
현대퓨처넷
현대해상
현대홈쇼핑
형지엘리트
혜인
호전실업
호텔신라
호텔신라우
화성산업
화승알앤에이
화승엔터프라이즈
화승인더
화승코퍼레이션
화신
화인베스틸
화천기계
화천기공
환인제약
황금에스티
효성
효성ITX
효성중공업
효성첨단소재
효성티앤씨
효성화학
후성
휠라홀딩스
휴니드
휴비스
휴스틸
휴켐스
흥국화재
흥국화재2우B
흥국화재우
흥아해운

##  일자별 OHLCV 조회

In [9]:
# get_market_ohlcv_by_date 함수는 시작일/종료일/티커 세 개의 파라미터를 입력받아 OHLCV를 일자별로 정렬
# DataFrame으로 반환


df = stock.get_market_ohlcv_by_date("20180604", "20210710", "005930")
print(df.head(5))

               시가     고가     저가     종가       거래량
날짜
2018-06-04  50800  51200  50700  51100   9767171
2018-06-05  51100  51400  50400  51300   9144100
2018-06-07  51800  51800  50500  50600  13590016
2018-06-08  50200  50400  49600  49650  16951706
2018-06-11  49750  50300  49350  49900  10571312

In [11]:
# get_market_ohlcv_by_date() 함수에 frequency 파라미터(d/m/y)를 추가
df = stock.get_market_ohlcv_by_date("20180604", "20210710", "005930", "m")
print(df.head(5))

               시가     고가     저가     종가        거래량
날짜
2018-06-30  50800  51800  45900  46650  239310263
2018-07-31  46500  47600  44650  46250  214539505
2018-08-31  46050  48450  43500  48450  194108773
2018-09-30  48200  48300  44000  46450  197984482
2018-10-31  46450  46800  40400  42400  234645485

In [ ]:
# 전 종목시세 가져오기

In [ ]:
import time
for ticker in stock.get_stock_ticker_list():
    df = stock.get_market_ohlcv_by_date("20181210", "20181212", ticker)
    print(df.head())
    time.sleep(1)

In [ ]:
# 코스피(KOSPI)/코스닥(KOSDAQ)/코넥스(KONEX) 시장을 지원합니다.
# ALL을 입력하면 전체 시장을 조회합니다.
# 값을 입력하지 않는다면 코스피 시장을 조회합니다.

df = stock.get_market_ohlcv_by_ticker("20200831", market="KOSPI")
df = stock.get_market_ohlcv_by_ticker("20200831", market="KOSDAQ")
df = stock.get_market_ohlcv_by_ticker("20200831", market="KONEX")

In [16]:
# 입력된 기간 동안의 가격 가격 변동 정보를 반환
df = stock.get_market_price_change_by_ticker("20210101", "20210701")
print(df.head())

            종목명      시가      종가    변동폭     등락률        거래량           거래대금
티커
095570   AJ네트웍스    4615    6000   1385  3001.0   22133467   110868110215
006840    AK홀딩스   25150   32750   7600  3022.0   13925129   423073601500
027410      BGF    4895    6560   1665  3401.0  124957204   825618297020
282330   BGF리테일  135500  170000  34500  2546.0    5958247   979520814358
138930  BNK금융지주    5680    7650   1970  3468.0  259963121  1754251271670

In [15]:
## get_market_price_change_by_ticker 함수는 기본적으로 KOSPI 시장을 조회
# market 파라미터에 KOSDAQ 또는 ALL을 입력할 수 있습니다. ALL은 모든 시장의 가격 변동폭을 조회
df = stock.get_market_price_change_by_ticker("20210101", "20210701", market="KOSDAQ")
print(df.head(3))

           종목명     시가     종가   변동폭     등락률       거래량           거래대금
티커
060310      3S   2165   3070   905  4180.0  56954259   153861012525
054620  APS홀딩스   8210  15850  7640  9306.0  33904464   375235767650
265520   AP시스템  24850  31200  6350  2555.0  47327276  1372604542250

## 종목별 DIV/BPS/PER/EPS 조회

In [17]:
df = stock.get_market_fundamental_by_ticker("20210108")
print(df.head())

          BPS        PER       PBR   EPS       DIV   DPS
티커
095570   6802   4.621094  0.669922   982  6.609375   300
006840  62448  11.687500  0.409912  2168  2.960938   750
027410  15699  17.453125  0.310059   281  2.240234   110
282330  36022  16.093750  3.910156  8763  1.910156  2700
138930  25415   3.509766  0.229980  1647  6.230469   360

In [23]:
#frequency 파라미터(d/m/y)를 추가
df = stock.get_market_fundamental_by_date("20200101", "20200430", "005930", freq="m")
print(df.head(2))

              BPS   PER   PBR   EPS   DIV   DPS
날짜
2020-01-31  35342  8.54  1.56  6461  2.57  1416
2020-02-29  35342  8.85  1.62  6461  2.48  1416

# 일자별 거래실적 추이 (거래대금)

In [24]:
#지정된 기간 동안의 일자별로 정렬된 (순매수) 거래량
df = stock.get_market_trading_value_by_date("20210101", "20210701", "005930")
print(df.head())

                    기관합계         기타법인             개인         외국인합계  전체
날짜
2021-01-04 -326136950200  48480486000   658901836000 -381245371800   0
2021-01-05 -203963791100   7236010900   622727193300 -425999413100   0
2021-01-06 -442463559600  13521042200  1013153304900 -584210787500   0
2021-01-07  250129976600  17802746700   -71008181500 -196924541800   0
2021-01-08 -436089196200   1958064400  -169881010800  604012142600   0

In [25]:
# 매수 혹은 매도 금액을 조회하고 싶다면 on 파라미터에 입력할 수 있습니다. 입력하지 않는다면 순매수 금액이 조회
df = stock.get_market_trading_value_by_date("20210115", "20210122", "005930", on='매도')
print(df.head())

                     기관합계         기타법인             개인         외국인합계  \
날짜
2021-01-15  1505250243300  19525756900   925426195700  525029741764
2021-01-18  1353223733500  22132983500  1883422627200  456996648400
2021-01-19  1205081446400  28155090000  1800734616800  407371601300
2021-01-20  1147190346800  10015618200   643413644500  405119540200
2021-01-21   878411497500  41184362100   851899126900  439714802000

                       전체
날짜
2021-01-15  2975231937664
2021-01-18  3715775992600
2021-01-19  3441342754500
2021-01-20  2205739149700
2021-01-21  2211209788500

In [28]:
#세 번째 파라미터에 KOSPI, KOSDAQ, KONEX를 사용하면 각 시장의 거래대금을 조회
#ALL을 입력하면 세 개의 시장을 합친 통합 거래대금을 조회
df = stock.get_market_trading_value_by_date("20210115", "20210122", "KOSPI")
print(df.head())

                     기관합계         기타법인             개인         외국인합계  전체
날짜
2021-01-15 -1414745885546  54444293672  2113924037705 -753622445831   0
2021-01-18  -278880716957 -26004926379   514299140387 -209413497051   0
2021-01-19   593956459208  21472281148 -1025418915468  409990175112   0
2021-01-20 -1234485992694  34510184945  1436793223994 -236817416245   0
2021-01-21  -292666343147 -13168420832   -62476631241  368311395220   0

In [29]:
# 시장의 거래대금을 조회할 때는 ETF, ETN ELW의 포함 여부를 지정할 수 있습니다. 
# 만약 값을 지정하지 않는다면 해당 데이터를 제외한 값을을 반환

df = stock.get_market_trading_value_by_date("20210115", "20210122", "KOSPI", etf=True, etn=True, elw=True)
print(df.head())

                     기관합계         기타법인             개인         외국인합계  전체
날짜
2021-01-15 -1536570309441  63110174617  2251672617980 -778212483156   0
2021-01-18  -601428111357 -27000808439   494341183227  134087736569   0
2021-01-19   544654406338  21787409868  -968965427363  402523611157   0
2021-01-20 -1227642472619  32139813590  1444113501769 -248610842740   0
2021-01-21  -284899892322 -19072459127   -61503500921  365475852370   0

In [30]:
# detail 옵션을 추가하면 상세한 정보를 얻을 수 있습니다. 옵션은 KOSPI, KOSDAQ, KONEX 조회할 때만 유효

df = stock.get_market_trading_value_by_date("20210115", "20210122", "KOSPI", etf=True, etn=True, elw=True, detail=True)
print(df.head())

                     금융투자            보험            투신           사모  \
날짜
2021-01-15  -991569370471 -101879326615  -73654664921 -47097103944
2021-01-18  -234901037556  -72240710086  101791257920 -22451555756
2021-01-19  1095649201830  -16407303019 -132856710155  12116061569
2021-01-20  -642974676550  -63074125224  -93392192931  -2355882539
2021-01-21   354360314201 -107524405663  -12601355617  21898580074

                      은행          기타금융           연기금         기타법인  \
날짜
2021-01-15  202104737955   -4226413080 -520248168365  63110174617
2021-01-18   29622542645    9331964150 -412580572674 -27000808439
2021-01-19    1776752770   -1933723125 -413689873532  21787409868
2021-01-20  -17889264145   -1573759250 -406382571980  32139813590
2021-01-21 -113225122905 -158268629075 -269539273337 -19072459127

                       개인           외국인       기타외국인  전체
날짜
2021-01-15  2251672617980 -780253717173  2041234017   0
2021-01-18   494341183227  132145345642  1942390927   0
2021-01-19  -968965427363  401864885550   658725607   0
2021-01-20  1444113501769 -250687123305  2076280565   0
2021-01-21   -61503500921  363801344664  1674507706   0

# 일자별 거래실적 추이 (거래량)

In [31]:
#일자별 시장의 거래량을 조회
df = stock.get_market_trading_volume_by_date("20210101", "20210701", "005930")
print(df.head())

               기관합계    기타법인        개인    외국인합계  전체
날짜
2021-01-04 -3986032  587931   8023833 -4625732   0
2021-01-05 -2477973   88391   7583287 -5193705   0
2021-01-06 -5326921  161660  12170137 -7004876   0
2021-01-07  2989615  213934   -837695 -2365854   0
2021-01-08 -5082378   22729  -1992264  7051913   0

In [32]:
# 매수 혹은 매도 거래량만을 조회하고 싶다면 on 파라미터에 입력 가능
# 입력하지 않는다면 순매수 수량이 조회
df = stock.get_market_trading_volume_by_date("20210115", "20210122", "005930", on='매도')
print(df.head())

                기관합계    기타법인        개인    외국인합계        전체
날짜
2021-01-15  16944750  216653  10371182  5899224  33431809
2021-01-18  15709256  258096  21942253  5318346  43227951
2021-01-19  13912581  323382  20956376  4702705  39895044
2021-01-20  13121791  114341   7346474  4628521  25211127
2021-01-21  10093381  473635   9714878  5036117  25318011

In [33]:
# 세 번째 파라미터에 KOSPI, KOSDAQ, KONEX를 사용하면 각 시장의 거래량을 조회 
#ALL을 입력하면 세 개의 시장을 합친 통합 거래량을 조회
df = stock.get_market_trading_volume_by_date("20210115", "20210122", "KOSPI")
print(df.head())

                기관합계     기타법인        개인     외국인합계  전체
날짜
2021-01-15 -20393142  8435634  29119751 -17162243   0
2021-01-18  -5700054 -1198498  15316328  -8417776   0
2021-01-19   7216278  -246496 -24395243  17425461   0
2021-01-20 -23038683  -793906  31606917  -7774328   0
2021-01-21 -18443990 -7082091   8365421  17160660   0

# 투자자별 거래실적 추이 (거래대금)

In [34]:
#지정된 기간 동안의 투자자별로 정렬된 (순매수) 거래대금
df = stock.get_market_trading_value_by_investor("20210101", "20210701", "005930")
print(df.head())

                   매도              매수            순매수
투자자구분
금융투자   31066223912100  28464867937600 -2601355974500
보험      1808485504300    779839009100 -1028646495200
투신      3177067544700   1794360840100 -1382706704600
사모      1259026093300    955202197900  -303823895400
은행       149110410100     87504448700   -61605961400

In [36]:
#세 번째 파라미터에 KOSPI, KOSDAQ, KONEX를 지정하면 각 시장의 거래대금을 조회
# ALL을 입력하면 세 개의 시장을 합친 통합 거래대금을 조회
df = stock.get_market_trading_value_by_investor("20210101", "20210701", "KOSPI")
print(df.head())

                    매도               매수            순매수
투자자구분
금융투자   129106291931852  124118597123721 -4987694808131
보험      14553591609599   11217910114022 -3335681495577
투신      30145646816976   25894892024771 -4250754792205
사모      16717352065581   13748646227789 -2968705837792
은행       2106750785171     829995794830 -1276754990341

In [37]:
#시장의 거래대금을 조회할 때는 ETF, ETN ELW의 포함 여부를 지정 가능
#만약 값을 지정하지 않는다면 해당 데이터를 제외한 값을을 반환
# 옵션은 KOSPI, KOSDAQ, KONEX 조회할 때만 유효
df = stock.get_market_trading_value_by_investor("20210115", "20210122", "KOSPI", etf=True, etn=True, elw=True)
print(df.head())

                   매도              매수           순매수
투자자구분
금융투자   15985568261831  15006116511544 -979451750287
보험      1219035502445    757575677208 -461459825237
투신      2235561259511   1799363743367 -436197516144
사모       999084910863    846067212945 -153017697918
은행       886226324790    936210985810   49984661020

# 투자자별 거래실적 추이 (거래량)

In [38]:
# 지정된 기간 동안의 투자자별로 정렬된 (순매수) 거래량
df = stock.get_market_trading_volume_by_investor("20210115", "20210122", "005930")
print(df.head())

             매도        매수      순매수
투자자구분
금융투자   29455909  26450600 -3005309
보험      1757287    509535 -1247752
투신      2950680   1721970 -1228710
사모       745727    696135   -49592
은행        38675     46394     7719

In [39]:
# 세 번째 파라미터에 KOSPI, KOSDAQ, KONEX를 지정하면 각 시장의 거래량을 조회
#ALL을 입력하면 세 개의 시장을 합친 통합 거래량을 조회
df = stock.get_market_trading_volume_by_investor("20210115", "20210122", "KOSPI")
print(df.head())

              매도         매수       순매수
투자자구분
금융투자   137969209  127697577 -10271632
보험      15737709    8577242  -7160467
투신      46872846   34307243 -12565603
사모      20780475   16342937  -4437538
은행       2236667     632814  -1603853

In [41]:
# 시장의 거래량을 조회할 때는 ETF, ETN ELW의 포함 여부를 지정 가능. 
# 만약 값을 지정하지 않는다면 해당 데이터를 제외한 값을을 반환. 
# 옵션은 KOSPI, KOSDAQ, KONEX 조회할 때만 유효
df = stock.get_market_trading_volume_by_investor("20210101", "20210701", "KOSPI", etf=True, etn=True, elw=True)
print(df.head())

                매도           매수         순매수
투자자구분
금융투자   45272762377  42606404777 -2666357600
보험       458281469    400048854   -58232615
투신      1321530638   1305211580   -16319058
사모       567744436    525209938   -42534498
은행       624072729    665814706    41741977

# 투자자별 순매수 상위종목

In [45]:
# get_market_net_purchases_of_equities_by_ticker 함수는 순매수 금액 순서로 정렬된 종목 리스트를 반환

df = stock.get_market_net_purchases_of_equities_by_ticker("20210625", "20210701", "KOSPI", "개인")
print(df.head())

            종목명     매도거래량     매수거래량   순매수거래량         매도거래대금         매수거래대금  \
티커
096770  SK이노베이션   4599070   6391059  1791989  1291281912500  1782192311500
005930     삼성전자  17454837  22843852  5389015  1419137816700  1849964333700
352820      하이브   1906810   3353418  1446608   568116193000   988493612000
035720      카카오  16142412  18581419  2439007  2533300845000  2921183894000
005935    삼성전자우   2917004   5101182  2184178   216899723400   379046574600

             순매수거래대금
티커
096770  490910399000
005930  430826517000
352820  420377419000
035720  387883049000
005935  162146851200

In [46]:
# 투자자 항목에는 다음 중 하나를 설정 가능
# 금융투자 / 보험 / 투신 / 사모 / 은행 / 기타금융 / 연기금 / 기관합계 / 기타법인 / 개인 / 외국인 / 기타외국인 / 전체

df = stock.get_market_net_purchases_of_equities_by_ticker("20210625", "20210701", "KOSPI", "외국인")
print(df.head())

               종목명    매도거래량    매수거래량  순매수거래량        매도거래대금        매수거래대금  \
티커
352820         하이브  1690323  2637060  946737  492731784500  757414908000
051910        LG화학   363204   631505  268301  306917404387  535622389387
006400       삼성SDI   308747   516205  207458  214852005815  362745255815
000660      SK하이닉스  3790389  4676690  886301  478636454556  596426755556
361610  SK아이이테크놀로지   471589   810119  338530   85095818500  145467791000

             순매수거래대금
티커
352820  264683123500
051910  228704985000
006400  147893250000
000660  117790301000
361610   60371972500

# 종목별 시가 총액 조회

In [48]:
# get_market_cap_by_ticker 함수는 특정 일자의 종목별 시가총액/거래량/거래대금/상장주식수/외국인보유주식수를 조회
#외국인보유주식수는 D-2 (영업일 기준)일 까지 유효한 값이 출력되며, D-1일은 0으로 표기
df = stock.get_market_cap_by_ticker("20210701")
print(df.head())

            종가             시가총액       거래량           거래대금       상장주식수
티커
005930   80100  478179582255000  13382882  1073188213795  5969782550
000660  124500   90636294442500   3336174   417469163256   728002365
035720  160000   71028733600000   4630280   748866494382   443929585
035420  413000   67840782135000    592869   246417898898   164263395
005935   73400   60399883780000   1288049    94562318306   822886700

In [51]:
# 일자별 시가 총액 조회
# get_market_cap_by_date 함수는 특정 종목의 일자별 시가총액을 조회
#거래량/거래대금/상장주식수가 함께 조회
df = stock.get_market_cap_by_date("20210101", "20210701", "005930")
print(df.head())
print(df.tail())

                       시가총액       거래량           거래대금       상장주식수
날짜
2021-01-04  495491951650000  38655276  3185356823460  5969782550
2021-01-05  500864755945000  35335669  2915618322800  5969782550
2021-01-06  490716125610000  42089013  3506903681680  5969782550
2021-01-07  494894973395000  32644642  2726112459660  5969782550
2021-01-08  530116690440000  59013307  5083939899952  5969782550
                       시가총액       거래량           거래대금       상장주식수
날짜
2021-06-25  487134256080000  13481405  1099148742353  5969782550
2021-06-28  488925190845000  11578529   946992165410  5969782550
2021-06-29  483552386550000  15744317  1277813841567  5969782550
2021-06-30  481761451785000  13288643  1075902355151  5969782550
2021-07-01  478179582255000  13382882  1073188213795  5969782550

In [55]:
#get_market_cap_by_date() 함수에 frequency 파라미터(d/m/y)를 추가
# d는 일자, m은 월, y는 연도를 의미
# 시가총액과 상장주식수는 월별 마지막 거래일의 값을 사용
df = stock.get_market_cap_by_date("20210101", "20210701", "005930", "m")
print(df.head())

                       시가총액        거래량            거래대금       상장주식수
날짜
2021-01-31  489522169100000  765471247  66588164494174  5969782550
2021-02-28  492507060375000  432953240  36020443268993  5969782550
2021-03-31  485940299570000  387612356  31876803021604  5969782550
2021-04-30  486537277825000  372938171  31169716082524  5969782550
2021-05-31  480567495275000  352211074  28341778034285  5969782550

In [59]:
# 시가총액과 상장주식수는 월별 마지막 거래일의 값을 사용

df = stock.get_market_cap_by_date("20210101", "20210701", "005930", "m")
print(df.head())
print(df)

                       시가총액        거래량            거래대금       상장주식수
날짜
2021-01-31  489522169100000  765471247  66588164494174  5969782550
2021-02-28  492507060375000  432953240  36020443268993  5969782550
2021-03-31  485940299570000  387612356  31876803021604  5969782550
2021-04-30  486537277825000  372938171  31169716082524  5969782550
2021-05-31  480567495275000  352211074  28341778034285  5969782550
                       시가총액        거래량            거래대금       상장주식수
날짜
2021-01-31  489522169100000  765471247  66588164494174  5969782550
2021-02-28  492507060375000  432953240  36020443268993  5969782550
2021-03-31  485940299570000  387612356  31876803021604  5969782550
2021-04-30  486537277825000  372938171  31169716082524  5969782550
2021-05-31  480567495275000  352211074  28341778034285  5969782550
2021-06-30  481761451785000  333099465  27047251878682  5969782550
2021-07-31  478179582255000   13382882   1073188213795  5969782550

# 티커별 외국인 보유량 및 외국인 한도소진률

In [70]:
# get_exhaustion_rates_of_foreign_investment_by_ticker 함수
#상장주식수/외국인한도수량/외국인보유수량/외국인한도소진률 정보를 조회
#외국인 보유수량 및 한도소진율은 장개시 시점 기준(금융감독원 외국인투자 관리시스템 제공 전일자 확정치)

df = stock.get_exhaustion_rates_of_foreign_investment_by_ticker('20210701')
print(df.head())
df

            상장주식수      보유수량        지분율       한도수량      한도소진율
티커
000020   27931470    828117   2.960938   27931470   2.960938
000040   96137368  44241720  46.031250   96137368  46.031250
000050   27415270    759750   2.769531   27415270   2.769531
000060  120625000  13175456  10.921875  120625000  10.921875
000070    8564271    742668   8.671875    8564271   8.671875

            상장주식수      보유수량        지분율       한도수량      한도소진율
티커
000020   27931470    828117   2.960938   27931470   2.960938
000040   96137368  44241720  46.031250   96137368  46.031250
000050   27415270    759750   2.769531   27415270   2.769531
000060  120625000  13175456  10.921875  120625000  10.921875
000070    8564271    742668   8.671875    8564271   8.671875
...           ...       ...        ...        ...        ...
383220    7661415    833803  10.882812    7661415  10.882812
383800   76280690  11459734  15.023438   76280690  15.023438
38380K    1465285    138831   9.468750    1465285   9.468750
900140   99455297  16400685  16.484375   99455297  16.484375
950210   60096155  38344916  63.812500   60096155  63.812500

[927 rows x 5 columns]

In [71]:
# 두 번째 파라미터 market은 코스피(KOSPI)/코스닥(KOSDAQ)/코넥스(KONEX) 시장을 지정해서 조회

df = stock.get_exhaustion_rates_of_foreign_investment_by_ticker('20200703', "KOSPI")
print(df.head())

            상장주식수      보유수량        지분율       한도수량      한도소진율
티커
000020   27931470   1400966   5.019531   27931470   5.019531
000040   91661018  43190959  47.125000   91661018  47.125000
000050   27415270    773627   2.820312   27415270   2.820312
000060  113680000  12968255  11.406250  113680000  11.406250
000070    8564271    661240   7.718750    8564271   7.718750

In [72]:
# 세 번째 파라미터 balance_limit을 True로 지정하면 외국인 보유한도의 제한 종목만 검색 rksmd
# 지정하지 않으면 False 

df = stock.get_exhaustion_rates_of_foreign_investment_by_ticker('20200703', "KOSPI",
balance_limit=True)
print(df.head())

            상장주식수       보유수량        지분율       한도수량      한도소진율
티커
003490   94844634   12350096  13.023438   47412833  26.046875
003495    1110794      29061   2.619141     555286   5.230469
015760  641964077  127919592  19.937500  256785631  49.812500
017670   80745711   28962369  35.875000   39565398  73.187500
020560  223235294   13871465   6.210938  111595323  12.429688

## 일자별 외국인 보유량 및 외국인 한도소진률

In [73]:
# et_exhaustion_rates_of_foreign_investment_by_date 함수는 특정한 종목의 일자별로 정렬된 상장주식수/외국인한도수량/외국인보유수량/외국인한도소진률 정보를 조회
# 외국인 보유수량 및 한도소진율은 장개시 시점 기준(금융감독원 외국인투자 관리시스템 제공 전일자 확정치)

df = stock.get_exhaustion_rates_of_foreign_investment_by_date("20210108", "20210115", "005930")
print(df.head())

                 상장주식수        보유수량       지분율        한도수량     한도소진율
날짜
2021-01-08  5969782550  3314966371  55.53125  5969782550  55.53125
2021-01-11  5969782550  3324115988  55.68750  5969782550  55.68750
2021-01-12  5969782550  3318676206  55.59375  5969782550  55.59375
2021-01-13  5969782550  3316551070  55.56250  5969782550  55.56250
2021-01-14  5969782550  3314652740  55.53125  5969782550  55.53125

## 인덱스 조회 API

In [77]:
# get_index_ticker_list() 함수는 코스피 인덱스를 리스트로 반환

tickers = stock.get_index_ticker_list()
print(tickers)

['1001', '1002', '1003', '1004', '1005', '1006', '1007', '1008', '1009', '1010', '1011', '1012', '1013', '1014', '1015', '1016', '1017', '1018', '1019', '1020', '1021', '1022', '1024', '1025', '1026', '1027', '1028', '1034', '1035', '1150', '1151', '1152', '1153', '1154', '1155', '1156', '1157', '1158', '1159', '1160', '1167', '1182', '1224', '1227', '1232', '1244']

In [80]:
tickers = stock.get_index_ticker_list("19800104")
print(tickers)

['1001', '1005', '1006', '1007', '1008', '1009', '1010', '1011', '1012', '1013', '1015', '1016', '1018', '1019', '1021', '1022', '1024', '1025', '1027']

In [81]:
# 코스닥 인덱스를 조회할 때는 market 옵션을 추가

tickers = stock.get_index_ticker_list(market='KOSDAQ')
print(tickers)

['2001', '2002', '2003', '2004', '2012', '2015', '2024', '2026', '2027', '2029', '2031', '2037', '2041', '2042', '2043', '2056', '2058', '2062', '2063', '2065', '2066', '2067', '2068', '2070', '2072', '2074', '2075', '2077', '2151', '2152', '2153', '2154', '2155', '2156', '2157', '2158', '2159', '2160', '2181', '2182', '2183', '2184', '2203', '2212', '2213', '2214', '2215', '2216', '2217', '2218']

In [83]:
# get_index_name 함수를 사용해서 티커의 이름

for ticker in stock.get_index_ticker_list():
    print(ticker, stock.get_index_ticker_name(ticker))

1001 코스피
1002 코스피 대형주
1003 코스피 중형주
1004 코스피 소형주
1005 음식료품
1006 섬유의복
1007 종이목재
1008 화학
1009 의약품
1010 비금속광물
1011 철강금속
1012 기계
1013 전기전자
1014 의료정밀
1015 운수장비
1016 유통업
1017 전기가스업
1018 건설업
1019 운수창고업
1020 통신업
1021 금융업
1022 은행
1024 증권
1025 보험
1026 서비스업
1027 제조업
1028 코스피 200
1034 코스피 100
1035 코스피 50
1150 코스피 200 커뮤니케이션서비스
1151 코스피 200 건설
1152 코스피 200 중공업
1153 코스피 200 철강/소재
1154 코스피 200 에너지/화학
1155 코스피 200 정보기술
1156 코스피 200 금융
1157 코스피 200 생활소비재
1158 코스피 200 경기소비재
1159 코스피 200 산업재
1160 코스피 200 헬스케어
1167 코스피 200 중소형주
1182 코스피 200 초대형제외 지수
1224 코스피 200 비중상한 30%
1227 코스피 200 비중상한 25%
1232 코스피 200 비중상한 20%
1244 코스피200제외 코스피지수

In [84]:
## 인덱스 구성종목 조회

# 인덱스를 구성하고 있는 종목의 티커를 리스트로 반환

pdf = stock.get_index_portfolio_deposit_file("1013")
print(len(pdf), pdf)

60 ['005930', '000660', '006400', '066570', '361610', '009150', '034220', '011070', '020150', '272210', '336260', '000990', '001440', '336370', '010120', '248070', '004490', '025540', '009450', '192650', '097520', '267260', '353200', '195870', '298040', '001820', '011930', '026890', '007340', '033180', '011690', '029530', '033240', '007810', '322000', '092220', '103590', '004710', '005680', '000300', '009470', '008700', '006340', '007660', '017900', '017040', '020760', '005870', '004770', '000500', '011230', '001210', '007610', '044380', '008110', '019490', '019180', '015260', '014910', '009140']

In [87]:
#  인덱스 OHLCV 조회
# get_index_ohlcv_by_date() 함수는 입력된 기간 동안의 인덱스 OHLCV를 조회

df = stock.get_index_ohlcv_by_date("20210601", "20210701", "1013")
print(df.head())
df

                  시가        고가        저가        종가        거래량           거래대금
날짜
2021-06-01  30151.15  30467.26  30005.75  30284.60  285777706  3013130482590
2021-06-02  30295.93  30509.45  30182.44  30249.67  212243845  3143606016255
2021-06-03  30247.11  31043.57  30247.11  30950.05  491314111  5299110838627
2021-06-04  30940.13  30940.13  30505.70  30792.65  417575114  3886262981630
2021-06-07  30830.22  31041.46  30636.15  30773.79  390617690  3999876683313

                  시가        고가        저가        종가        거래량           거래대금
날짜
2021-06-01  30151.15  30467.26  30005.75  30284.60  285777706  3013130482590
2021-06-02  30295.93  30509.45  30182.44  30249.67  212243845  3143606016255
2021-06-03  30247.11  31043.57  30247.11  30950.05  491314111  5299110838627
2021-06-04  30940.13  30940.13  30505.70  30792.65  417575114  3886262981630
2021-06-07  30830.22  31041.46  30636.15  30773.79  390617690  3999876683313
2021-06-08  30773.15  30880.77  30588.81  30646.31  706548595  4795804523892
2021-06-09  30546.08  30567.66  30214.83  30214.83  483387763  4041239477690
2021-06-10  30218.08  30332.01  30114.09  30207.52  354478021  3943026195616
2021-06-11  30221.10  30576.77  30221.10  30518.08  251485407  3864539909864
2021-06-14  30500.29  30500.29  30318.18  30393.49  134271277  2505403994589
2021-06-15  30413.17  30688.48  30413.17  30609.84  373874551  3262372478935
2021-06-16  30608.97  30893.66  30608.97  30880.75  346278462  3367755468217
2021-06-17  30876.56  30876.56  30418.65  30546.91  390811401  3266789231770
2021-06-18  30555.61  30700.82  30482.91  30524.87  200640784  3427372833310
2021-06-21  30505.63  30505.63  30133.07  30307.43  300260775  3998435757730
2021-06-22  30313.19  30477.76  30275.18  30349.46  466479348  3680912732793
2021-06-23  30349.04  30504.22  30317.38  30414.21  290851227  3611593632096
2021-06-24  30487.67  30893.38  30472.53  30840.31  336091841  4408627600009
2021-06-25  30904.61  31138.12  30891.54  31030.79  252437761  3196514354793
2021-06-28  31059.17  31147.13  30877.18  30978.01  101839990  2472217682705
2021-06-29  31013.34  31080.76  30664.56  30745.04  115520518  2911262345845
2021-06-30  30764.46  31036.58  30764.46  30846.29   91190866  3024632368646
2021-07-01  30859.01  30870.75  30646.03  30680.64   95414744  3064729183327

In [99]:
# get_index_ohlcv_by_date() 함수에 frequency 파라미터(d/m/y)를 추가 rksmd
# d는 일자, m은 월, y는 연도를 의미

df = stock.get_index_ohlcv_by_date("20210101", "202106030", "1013", "m")
print(df.head())

                  시가        고가        저가        종가         거래량
날짜
2021-01-31  29793.56  35271.50  29793.56  30849.19  4498806152
2021-02-28  30849.24  32762.32  30341.24  31278.98  2723331288
2021-03-31  31294.71  32477.33  30089.66  30724.75  2053732804
2021-04-30  31010.38  32538.56  30576.85  30626.15  2528155211
2021-05-31  30624.48  31244.39  29072.96  30169.07  2029219840

In [102]:
# 인덱스 등락률 조회

#get_index_price_change_by_ticker() 함수는 지수의 등락률/거래량/거래대금을 반환
# KRX / KOSPI / KOSDAQ 세 개의 지수를 지원

df = stock.get_index_price_change_by_ticker("20210101", "20210630", "KOSDAQ")
print(df.head())

                        시가       종가        등락률           거래량              거래대금
지수명
코스닥                 968.42  1029.96   6.351562  271152394443  1476958803219536
코스닥 150            1532.52  1464.08  -4.468750   12266377117   348535041006838
코스닥 150 정보기술        812.05   840.79   3.539062    4261931849    82919528005520
코스닥 150 헬스케어       5578.37  4516.31 -19.046875    2219363960   130789715876673
코스닥 150 커뮤니케이션서비스  2684.58  3169.51  18.062500     575556345    31802552690080

In [ ]:
df = stock.get_index_price_change_by_ticker("20210101", "20210630", "KOSDAQ")
print(df)

## 공매도 API##

In [ ]:
# KRX는 (T+2)일 이후의 데이터를 제공

In [104]:
##종목별 공매도 현황
## get_shorting_status_by_date() 메서드는 시작일/종료일/티커 세 개의 파라미터를 입력받아 공매도 현황을 DataFrame으로 반환

df = stock.get_shorting_status_by_date("20210101", "20210630", "005930")
print(df)

               거래량     잔고수량         거래대금          잔고금액
날짜
2021-01-04    9279  2722585    771889500  225974555000
2021-01-05     169  2676924     14011100  224593923600
2021-01-06     967  3002548     80855100  246809445600
2021-01-07     763  2447030     63634800  202858787000
2021-01-08       6  2319328       534000  205956326400
...            ...      ...          ...           ...
2021-06-24  105380  2572263   8512996100  208867755600
2021-06-25   20054  2199798   1635613900  179503516800
2021-06-28  149219  2396700  12207353100  196289730000
2021-06-29   67041  2672204   5446077900  216448524000
2021-06-30   52239  2537611   4227950500  204785207700

[123 rows x 4 columns]

In [106]:
#종목별 공매도 거래 정보
# get_shorting_volume_by_ticker 함수는 입력받은 일자의 공매도 거래량 정보를 반환

df = stock.get_shorting_volume_by_ticker("20210125")
print(df.head(10))

          공매도       매수    비중
티커
095570     32   180458  0.02
006840     79   386257  0.02
027410  18502  8453962  0.22
282330     96    82986  0.12
138930   1889  1181748  0.16
001460      0      368  0.00
001465      0      124  0.00
001040    330   139537  0.24
079160    117   829827  0.01
00104K      0    13447  0.00

In [107]:
# 코스피(KOSPI)/코스닥(KOSDAQ)/코넥스(KONEX)의 공매도 거래량을 조회
# 사용하지 않을 경우 코스피가 선택

df = stock.get_shorting_volume_by_ticker("20210125", "KOSDAQ")
print(df.head())

        공매도       매수    비중
티커
060310    0   328833  0.00
054620    0   106187  0.00
265520    0   285869  0.00
211270    0  1373332  0.00
035760   18   291125  0.01

In [113]:
## 조회하려는 증권의 세부 종류를 리스트로 지정 가능
# 리스트에 사용될 수 있는 상세 구분항목(식, ETF, ETN, ELW, 신주인수권증서및증권, 수익증권

df = stock.get_shorting_volume_by_ticker("20210630", include=["주식", "ELW"])
print(df.head())

          공매도      매수         비중
티커
095570    352   38568   0.910000
006840    104   24101   0.430000
027410    743  183702   0.400000
282330  12200   55771  21.879999
138930  38071  821684   4.630000

In [115]:
## 일자별 공매도 거래 현황
# get_shorting_volume_by_date() 함수는 입력받은 종목에 대해 주어진 기간 동안의 공매도 거래 정보를 반환

df = df = stock.get_shorting_volume_by_date("20210104", "20210108", "005930")
print(df.head(3))
print(df)

             공매도        매수    비중
날짜
2021-01-04  9279  38655276  0.02
2021-01-05   169  35335669  0.00
2021-01-06   967  42089013  0.00
             공매도        매수    비중
날짜
2021-01-04  9279  38655276  0.02
2021-01-05   169  35335669  0.00
2021-01-06   967  42089013  0.00
2021-01-07   763  32644642  0.00
2021-01-08     6  59013307  0.00

In [117]:
## 투자자별 공매도 거래 현황 (거래량)

# get_shorting_investor_volume_by_date 함수는 시작일/종료일 두 개의 파라미터를 입력받아 
# 해당 기간동안 코스피 종목의 투자자별 공매도 거래량을 DataFrame으로 반환

df = stock.get_shorting_investor_volume_by_date("20210101", "20210630", "KOSPI")
print(df.head())
df

                 기관      개인      외국인    기타        합계
날짜
2019-04-01  3402249  133996  5702788   200   9239233
2019-04-02  2883434  139801  5580395     0   8603630
2019-04-03  3589910  127075  6375248     0  10092233
2019-04-04  3200221  119193  5604505  1405   8925324
2019-04-05  3163018  134396  6882981  1754  10182149

                 기관      개인      외국인    기타        합계
날짜
2019-04-01  3402249  133996  5702788   200   9239233
2019-04-02  2883434  139801  5580395     0   8603630
2019-04-03  3589910  127075  6375248     0  10092233
2019-04-04  3200221  119193  5604505  1405   8925324
2019-04-05  3163018  134396  6882981  1754  10182149

In [119]:
## 투자자별 공매도 거래 현황 (거래대금)

# get_shorting_investor_value_by_date 함수는 시작일/종료일 두 개의 파라미터를 입력받아 
# 해당 기간동안 코스피 종목의 투자자별 공매도 거래대금을 DataFrame으로 반환

df = stock.get_shorting_investor_value_by_date("20210101", "20210630", "KOSPI")
print(df.head())
df

                     기관  개인  외국인  기타           합계
날짜
2021-01-04  31128651988   0    0   0  31128651988
2021-01-05  13862504742   0    0   0  13862504742
2021-01-06  12510404426   0    0   0  12510404426
2021-01-07   8899480971   0    0   0   8899480971
2021-01-08  15758050170   0    0   0  15758050170

                      기관           개인           외국인  기타            합계
날짜
2021-01-04   31128651988            0             0   0   31128651988
2021-01-05   13862504742            0             0   0   13862504742
2021-01-06   12510404426            0             0   0   12510404426
2021-01-07    8899480971            0             0   0    8899480971
2021-01-08   15758050170            0             0   0   15758050170
...                  ...          ...           ...  ..           ...
2021-06-24  183822212146  12420609845  329382437920   0  525625259911
2021-06-25  101991111007   9682281080  224340476605   0  336013868692
2021-06-28   91486482740   8716763155  256057217960   0  356260463855
2021-06-29   82123591299   6610141970  205843886040   0  294577619309
2021-06-30   73197127905   7998832135  228833972965   0  310029933005

[123 rows x 5 columns]

In [121]:
# 코스닥의 공매도 거래량 또한 조회

df = stock.get_shorting_investor_value_by_date("20210101", "20210630", "KOSDAQ")
print(df.head())
df

                    기관  개인  외국인  기타          합계
날짜
2021-01-04  7067302914   0    0   0  7067302914
2021-01-05  2515010711   0    0   0  2515010711
2021-01-06  1378114484   0    0   0  1378114484
2021-01-07  2243141551   0    0   0  2243141551
2021-01-08  2552581359   0    0   0  2552581359

                     기관          개인           외국인        기타            합계
날짜
2021-01-04   7067302914           0             0         0    7067302914
2021-01-05   2515010711           0             0         0    2515010711
2021-01-06   1378114484           0             0         0    1378114484
2021-01-07   2243141551           0             0         0    2243141551
2021-01-08   2552581359           0             0         0    2552581359
...                 ...         ...           ...       ...           ...
2021-06-24  31912169930  2674261870  114606090170  16600600  149209122570
2021-06-25  20869102817  1900162450   76534190885         0   99303456152
2021-06-28  15104973560  2018362300   76967223045         0   94090558905
2021-06-29  59120395965  3218755240   78425611080         0  140764762285
2021-06-30  28950523110  2096963290   70923208280         0  101970694680

[123 rows x 5 columns]

In [122]:
## 종목별 공매도 잔고 현황
# get_shorting_balance_by_date 메서드는 시작일/종료일 두 개의 파라미터를 입력받아 
# 해당 기간동안 공매도 잔고 정보를 DataFrame으로 반환

df = stock.get_shorting_balance_by_date("20210101", "2021063005", "005930")
print(df.head())

              공매도잔고       상장주식수         공매도금액          시가총액    비중
날짜
2021-01-04  2722585  5969782550  225974555000  4.954920e+14  0.05
2021-01-05  2676924  5969782550  224593923600  5.008648e+14  0.04
2021-01-06  3002548  5969782550  246809445600  4.907161e+14  0.05
2021-01-07  2447030  5969782550  202858787000  4.948950e+14  0.04
2021-01-08  2319328  5969782550  205956326400  5.301167e+14  0.04

In [125]:
## 공매도 거래비중 상위 50 종목

# get_shorting_trade_top50 메서드는 조회일자를 입력받아 
# 해당일 코스피 종목의 거래 비중 TOP 50을 DataFrame으로 반환 거래 비중은 거래대금/거래대금로 계산
df = stock.get_shorting_volume_top50("20210712")
print(df.head())
df

        순위     공매도거래대금        총거래대금  공매도비중  직전40일거래대금평균  공매도거래대금증가율  \
티커
002790   1  1501798200   7711130000  19.48   1259745110        1.19
007570   2   843160100   4798047250  17.57    491583396        1.72
010130   3  2725768500  16115343000  16.91    824159700        3.31
000120   4   677466000   4279560500  15.83    632997475        1.07
090430   5  3628227000  23229677500  15.62   6522323638        0.56

        직전40일공매도평균비중  공매도비중증가율  주가수익률
티커
002790          8.61      2.26   1.31
007570          5.91      2.98  -0.42
010130          4.41      3.83   0.59
000120          7.80      2.03  -0.28
090430         11.49      1.36   0.83

,순위,공매도거래대금,총거래대금,공매도비중,직전40일거래대금평균,공매도거래대금증가율,직전40일공매도평균비중,공매도비중증가율,주가수익률
티커,,,,,,,,,
002790,1,1501798200,7711130000,19.48,1259745110,1.19,8.61,2.26,1.31
007570,2,843160100,4798047250,17.57,491583396,1.72,5.91,2.98,-0.42
010130,3,2725768500,16115343000,16.91,824159700,3.31,4.41,3.83,0.59
000120,4,677466000,4279560500,15.83,632997475,1.07,7.80,2.03,-0.28
090430,5,3628227000,23229677500,15.62,6522323638,0.56,11.49,1.36,0.83
016360,6,1235520450,7944431250,15.55,815133478,1.52,5.23,2.97,0.47
011200,7,31610946300,211139225950,14.97,24698707579,1.28,5.83,2.57,-1.90
036570,8,17368971000,119023908000,14.59,4403806275,3.94,6.73,2.17,-3.50
010060,9,3655480000,27544488000,13.27,3652484588,1.00,6.93,1.91,-0.88
000150,10,1540234500,11625555500,13.25,1339788120,1.15,7.85,1.69,4.97
010780,11,356047500,2690438000,13.23,448977643,0.79,9.92,1.33,0.18
008770,12,2402894500,19205082200,12.51,2414621043,0.99,4.37,2.87,0.65
003240,13,122133000,994822000,12.28,63141475,1.93,3.76,3.27,2.40
073240,14,513245980,4259458160,12.05,818996959,0.63,5.17,2.33,0.86
114090,15,585178500,4868493700,12.02,540253448,1.08,5.62,2.14,0.61
005940,16,473691950,3942870950,12.01,647948910,0.73,6.46,1.86,1.63
023530,17,1216417500,10166112000,11.96,1961777475,0.62,13.51,0.89,2.78
282330,18,426855000,3574802000,11.94,658887713,0.65,11.17,1.07,2.45
005830,19,593706400,5075325900,11.70,946677124,0.63,10.73,1.09,2.80
004170,20,1854558000,16007824000,11.59,1396683113,1.33,3.76,3.08,1.10
011790,21,3605308500,32291179000,11.16,2549688963,1.41,5.79,1.93,-0.31
047050,22,1433717750,13383136700,10.71,979355564,1.46,5.35,2.00,-0.63
051900,23,2484499000,23431438000,10.60,4860512275,0.51,8.83,1.20,0.35
128940,24,1179534000,11139093500,10.59,1480323463,0.80,6.21,1.70,1.18
034220,25,3689127450,34888285850,10.57,10083223674,0.37,11.86,0.89,0.65
007070,26,665630000,6370887550,10.45,1451756354,0.46,9.17,1.14,0.28
285130,27,967300500,9422546500,10.27,1067002450,0.91,5.38,1.91,0.20
021240,28,970580400,9567493000,10.14,1692400433,0.57,7.59,1.34,2.50
001800,29,196796950,1946693750,10.11,216125611,0.91,6.44,1.57,3.13
161890,30,674140800,6673071100,10.10,339797435,1.98,3.03,3.34,1.65
066570,31,12528364000,124493939000,10.06,6889055150,1.82,4.87,2.06,-0.31
003850,32,241660950,2430053500,9.95,221487019,1.09,2.99,3.33,1.59
052690,33,4670342800,47132773700,9.91,1017071181,4.59,1.77,5.58,-3.39
026960,34,416787750,4326783900,9.63,237790314,1.75,6.51,1.48,0.67
185750,35,977774500,10220751000,9.57,449304550,2.18,5.60,1.71,1.50
001680,36,346952450,3705545450,9.36,324463313,1.07,3.52,2.66,0.00
009830,37,3992925350,43502109350,9.18,6329016424,0.63,9.62,0.95,-0.35
007310,38,175640000,1935525000,9.07,292635875,0.60,6.47,1.40,0.95
010140,39,3355062770,37848877130,8.86,3069695262,1.09,6.37,1.39,1.68
004370,40,602350500,6886022500,8.75,1177272188,0.51,8.05,1.09,0.65
033780,41,2494067600,29229080800,8.53,1532870775,1.63,3.88,2.20,1.70
003090,42,1564348500,18449407500,8.48,1206818963,1.30,5.63,1.50,1.72
028670,43,3218155250,38013029130,8.47,3531540729,0.91,5.87,1.44,-0.88
011170,44,1939782500,22924487500,8.46,3909603225,0.50,7.43,1.14,0.79
057050,45,140174300,1695408300,8.27,44250758,3.17,1.81,4.58,0.93
009420,46,487184050,5908798000,8.24,184985670,2.63,2.38,3.47,2.61
008560,47,656080670,8001466430,8.20,1059639370,0.62,10.16,0.81,3.12
000100,48,562569900,7023544600,8.01,938076483,0.60,6.71,1.19,0.65
017670,49,4675604500,58380052000,8.01,3916253138,1.19,5.80,1.38,1.40
192080,50,407218700,5188834000,7.85,340736988,1.20,3.59,2.19,1.49

In [126]:
# 코스닥의 공매도 거래량 또한 조회

df = stock.get_shorting_volume_top50("20210712", "KOSDAQ")
print(df.head())

        순위     공매도거래대금       총거래대금  공매도비중  직전40일거래대금평균  공매도거래대금증가율  \
티커
060250   1  1073692500  5309090800  20.22    604351160        1.78
137400   2  1052096400  5268390400  19.97    385582949        2.73
006730   3   330441220  1673941880  19.74    161378333        2.05
039200   4  1217867850  6438548800  18.91    901023628        1.35
218410   5   718604350  3839008850  18.72    498229565        1.44

        직전40일공매도평균비중  공매도비중증가율  주가수익률
티커
060250          9.32      2.17  -1.53
137400          9.25      2.16  -0.21
006730          4.45      4.43   3.05
039200          7.92      2.39  -1.37
218410          6.48      2.89  -1.57

In [127]:
## 종목별 공매도 잔고 TOP 50
# get_shorting_balance_top50 메서드는 조회 일자를 입력받아 
# 공매도 비중이 높은 상위 50개 종목 정보를 반환 공매비중은 공매도 잔고/상장주식수로 계산

df = stock.get_shorting_balance_top50("20210712")
print(df.head())

        순위     공매도잔고      상장주식수         공매도금액          시가총액        비중
티커
032350   1   5024074   69275662   99225461500  1.368194e+12  7.250000
034220   2  18146165  357815700  420991028000  8.301324e+12  5.070312
097520   3    831042   17863482   37563098400  8.074294e+11  4.648438
019170   4   2379564   52984990  155385529200  3.459920e+12  4.488281
034020   5  15087308  427675765  384726354000  1.090573e+13  3.529297

In [128]:
# 코스닥 또한 거래량을 조회
df = stock.get_shorting_balance_top50("20210712", market="KOSDAQ")
print(df.head())

        순위    공매도잔고      상장주식수         공매도금액          시가총액        비중
티커
215600   1  6489694   71617125   78525297400  8.665672e+11  9.062500
032500   2  3188478   39820883  161336986800  2.014937e+12  8.007812
028300   3  7329918  106077594  247751228400  3.585423e+12  6.910156
096530   4  2718828   52225994  239256864000  4.595887e+12  5.210938
048410   5  1702807   36551277   60194227450  1.292088e+12  4.660156

## 채권 API

In [131]:
# 장외일자별 채권수익률
df = bond.get_treasury_yields_in_kerb_market("20190208")

NameError: name 'bond' is not defined