In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
cd /content/drive/MyDrive/UBION_final_project/data

/content/drive/MyDrive/UBION_final_project/data

In [ ]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [ ]:
df = pd.read_csv("v7_final.csv", encoding='cp949')
df

            회사명  거래소코드  ... EBITDA/평균발행주식수(백만원)  EV/EBITDA(배)
0      (주)CMG제약  58820  ...             -104.44          0.00
1      (주)CMG제약  58820  ...             -221.19           NaN
2      (주)CMG제약  58820  ...             -443.98           NaN
3      (주)CMG제약  58820  ...             -243.34           NaN
4      (주)CMG제약  58820  ...               46.75         18.52
...         ...    ...  ...                 ...           ...
25116   흥아해운(주)   3280  ...              267.91         13.12
25117   흥아해운(주)   3280  ...               66.90         36.60
25118   흥아해운(주)   3280  ...              -97.94          0.00
25119   흥아해운(주)   3280  ...               46.96         58.29
25120   흥아해운(주)   3280  ...               82.31         29.04

[25121 rows x 174 columns]

# 같은 회사명에 거래소 코드가 여러개인 애가 있음

In [ ]:
check = df.groupby(['회사명'])['거래소코드'].nunique().reset_index()
check.rename(columns={'거래소코드':'거래소코드_갯수'}, inplace=True)
check = check[ check['거래소코드_갯수']>1]

In [ ]:
check_df = df[df['회사명'].isin(check['회사명'].tolist())]
check_df = check_df.reset_index()
check_df

     index       회사명   거래소코드  ... EBITDA/금융비용(배)  EBITDA/평균발행주식수(백만원)  EV/EBITDA(배)
0     3589     (주)본느  226340  ...         207.10               246.64         15.29
1     3590     (주)본느  226340  ...          22.67               133.14         15.62
2     3591     (주)본느  242420  ...          24.32              1005.82         -1.07
3     3592     (주)본느  226340  ...            NaN                  NaN           NaN
4     3593     (주)본느  242420  ...         138.05               755.41         -0.62
..     ...       ...     ...  ...            ...                  ...           ...
265  23432  패션플랫폼(주)  256090  ...          76.54              1734.97          0.01
266  23433  패션플랫폼(주)  225590  ...            NaN                  NaN           NaN
267  23434  패션플랫폼(주)  225590  ...          61.11               212.41          4.70
268  23435  패션플랫폼(주)  225590  ...          58.30               373.85          3.46
269  23436  패션플랫폼(주)  225590  ...          22.17               163.20          8.09

[270 rows x 175 columns]

In [ ]:
check_df.groupby(['회사명','거래소코드'])['index'].count().reset_index()

            회사명   거래소코드  index
0         (주)본느  226340      6
1         (주)본느  242420      2
2      (주)세화피앤씨   85980      4
3      (주)세화피앤씨  252500      5
4      (주)신성이엔지   11930     14
5      (주)신성이엔지  104110      8
6    (주)아이엘사이언스  122050      1
7    (주)아이엘사이언스  307180      3
8       (주)알로이스  271400      2
9       (주)알로이스  297570      3
10     (주)엔케이맥스  182400      6
11     (주)엔케이맥스  262760      1
12       (주)인산가   62580      3
13       (주)인산가  277410      4
14      (주)인터파크   35080     14
15      (주)인터파크  108790      6
16       (주)자비스  230400      4
17       (주)자비스  254120      5
18       (주)정다운  208140      7
19       (주)정다운  224090      1
20    (주)카이노스메드  220250      5
21    (주)카이노스메드  284620      3
22   (주)티에스트릴리온  284610      3
23   (주)티에스트릴리온  317240      2
24      (주)판타지오   32800     14
25      (주)판타지오  187770      1
26  (주)포인트엔지니어링  176560      2
27  (주)포인트엔지니어링  256630      4
28       (주)풀무원   17810     14
29       (주)풀무원  103160      1
30     (주)한국비엔씨  226610      4
31     (주)한국비엔씨  256840      5
32     (주)핸디소프트   32380      3
33     (주)핸디소프트  220180      5
34      나무기술(주)  167380      2
35      나무기술(주)  242040      5
36      삼성물산(주)     830      8
37      삼성물산(주)   28260      7
38     소프트캠프(주)  210610      5
39     소프트캠프(주)  258790      4
40     씨아이에스(주)  144630      2
41     씨아이에스(주)  222080      6
42      에스와이(주)    4530      1
43      에스와이(주)  109610      6
44      에스케이(주)    3600      8
45      에스케이(주)   34730     12
46     엔에이치엔(주)   35420      1
47     엔에이치엔(주)  181710      8
48   엠에프엠코리아(주)  251960      4
49   엠에프엠코리아(주)  323230      2
50      줌인터넷(주)  229480      3
51      줌인터넷(주)  239340      5
52     케이엠제약(주)  225430      6
53     케이엠제약(주)  237720      3
54     패션플랫폼(주)  225590      6
55     패션플랫폼(주)  256090      1

In [ ]:
# 합병등과 같은 이유로 거래소코드가 2개인 경우 데이터프레임에서 삭제
df = df[~df['회사명'].isin(check_df['회사명'])]

# 거래소코드가 같은데 회사명이 두개인 경우가 있었음

In [ ]:
check = df.groupby(['거래소코드'])['회사명'].nunique().reset_index()
check[check['회사명']>1]

     거래소코드  회사명
759  30790    2
791  32640    2

In [ ]:
print( df[df['거래소코드']==30790]['회사명'].unique() )
# '동양시스템즈(주) -> '비케이탑스(주)'

df.loc[df['회사명']=='동양시스템즈(주)', '회사명'] = '비케이탑스(주)'

['동양시스템즈(주)' '비케이탑스(주)']

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [ ]:
print( df[df['거래소코드']==32640]['회사명'].unique() )
#'(주)엘지텔레콤' -> '(주)엘지유플러스'

df.loc[df['회사명']=='(주)엘지텔레콤', '회사명'] = '(주)엘지유플러스'

['(주)엘지유플러스' '(주)엘지텔레콤']

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [ ]:
check = df.groupby(['거래소코드'])['회사명'].nunique().reset_index()
check[check['회사명']>1]

Empty DataFrame
Columns: [거래소코드, 회사명]
Index: []

# preprocessing

In [ ]:
df = df[~df['산업코드'].isnull()]

In [ ]:
df['산업코드'] = df['산업코드'].astype(int)
df['산업코드'] = df['산업코드'].astype(str).str.zfill(6)
df['산업대분류'] = df['산업코드'].str[:2]

In [ ]:
df = df[df['산업대분류'].isin(['03','10','07'])]

# 결측치

In [ ]:
df.isnull().sum(0).reset_index().sort_values(by=0, ascending=False).head(20)

                              index      0
6                             상장폐지일  18887
135  종업원1인당 경상이익 (2007년 이전 발생)(백만원)   7437
38              투자수익률 (2007년 이전 발생)   7436
31          자기자본경상이익률 (2007년 이전 발생)   7436
66         1주당경상이익 (2007년 이전 발생)(원)   7436
24           매출액경상이익률 (2007년 이전 발생)   7436
34           자본금경상이익률 (2007년 이전 발생)   7436
12            경상이익증가율 (2007년 이전 발생)   7436
28           총자본경상이익률 (2007년 이전 발생)   7436
37            기업경상이익률 (2007년 이전 발생)   7436
173                    EV/EBITDA(배)   1033
146                           자본분배율    254
145                         노동소득분배율    254
144                           부가가치율    254
143                          기계투자효율    254
142                          설비투자효율    254
139                           기계장비율    254
141                         총자본투자효율    254
140                           자본집약도    254
138                           노동장비율    254

In [ ]:
# EV/EBITDA(배) NULL값이 너무 많기 때문에 값 채우기
df['EV/EBITDA(배)'] = round(df['기업가치(EV)(백만원)']/df['EBITDA(백만원)'], 3)
df.loc[(df['EV/EBITDA(배)'] < 0), 'EV/EBITDA(배)'] = 0

In [ ]:
df.isnull().sum(0).reset_index().sort_values(by=0, ascending=False).head(20)

                              index      0
6                             상장폐지일  18887
135  종업원1인당 경상이익 (2007년 이전 발생)(백만원)   7437
38              투자수익률 (2007년 이전 발생)   7436
24           매출액경상이익률 (2007년 이전 발생)   7436
66         1주당경상이익 (2007년 이전 발생)(원)   7436
31          자기자본경상이익률 (2007년 이전 발생)   7436
34           자본금경상이익률 (2007년 이전 발생)   7436
12            경상이익증가율 (2007년 이전 발생)   7436
28           총자본경상이익률 (2007년 이전 발생)   7436
37            기업경상이익률 (2007년 이전 발생)   7436
146                           자본분배율    254
145                         노동소득분배율    254
144                           부가가치율    254
143                          기계투자효율    254
142                          설비투자효율    254
139                           기계장비율    254
141                         총자본투자효율    254
140                           자본집약도    254
138                           노동장비율    254
137                 종업원1인당 인건비(백만원)    254

In [ ]:
col_list = df.columns

drop_col = [s for s in col_list if "2007" in s] 
df.drop(drop_col, axis=1, inplace=True)

In [ ]:
df.isnull().sum(0).reset_index().sort_values(by=0, ascending=False).head(20)

                          index      0
6                         상장폐지일  18887
158  PSR(Price sales ratio)(최저)    254
131                       자본집약도    254
140       법인세비용차감전(계속사업)손익(백만원)    254
139                 부가가치(백만원).1    254
138                       이윤분배율    254
137                       자본분배율    254
136                     노동소득분배율    254
135                       부가가치율    254
133                      설비투자효율    254
132                     총자본투자효율    254
130                       기계장비율    254
142                   금융비용(백만원)    254
129                       노동장비율    254
128             종업원1인당 인건비(백만원)    254
127             종업원1인당 순이익(백만원)    254
126             종업원1인당 매출액(백만원)    254
125            종업원1인당 부가가치(백만원)    254
124                   부가가치(백만원)    254
160                 EBITDA(백만원)    254

In [ ]:
df['NaN_cnt'] = df.isnull().sum(1)
df['NaN_cnt'].value_counts()

1      18640
0       2060
158      228
159       15
157        9
28         2
16         2
Name: NaN_cnt, dtype: int64

In [ ]:
tmp = df.copy()
tmp['상장폐지년도'] = tmp['상장폐지일'].str[0:4]
tmp['회계년도__'] = tmp['회계년도'].str[0:4]

In [ ]:
tmp = tmp.loc[~tmp['상장폐지년도'].isnull(),['회사명','회계년도','회계년도__', '상장폐지일','상장폐지년도']]
tmp[tmp['회계년도__'] == tmp['상장폐지년도']]

                회사명     회계년도 회계년도__       상장폐지일 상장폐지년도
754       (주)네프로아이티  2011/03   2011  2011/11/05   2011
4181          (주)소예  2009/06   2009  2009/11/03   2009
5523        (주)알에스넷  2012/06   2012  2012/12/05   2012
9027      (주)제너시스템즈  2013/03   2013  2013/07/12   2013
9955         (주)케이알  2009/03   2009  2009/08/21   2009
11847     (주)플러스프로핏  2009/06   2009  2009/11/20   2009
12905        (주)휴리프  2009/03   2009  2009/07/15   2009
19032      케이비물산(주)  2012/01   2012  2012/06/08   2012
19946  한국유나이티드제약(주)  2007/03   2007  2007/10/23   2007

In [ ]:
tmp

   index           회사명  회계년도 상장폐지년도
0    754     (주)네프로아이티  2011   2011
1   4181         (주)소예  2009   2009
2   5523       (주)알에스넷  2012   2012
3   9027     (주)제너시스템즈  2013   2013
4   9955        (주)케이알  2009   2009
5  11847     (주)플러스프로핏  2009   2009
6  12905        (주)휴리프  2009   2009
7  19032      케이비물산(주)  2012   2012
8  19946  한국유나이티드제약(주)  2007   2007

In [ ]:
df = df.reset_index()
df[df['index'].isin(find)]

       level_0  index         회사명  ...  EV/EBITDA(배) 산업대분류 NaN_cnt
604        604    754       (주)남성  ...        17.849    07       1
4575      4575   5523    (주)신영와코루  ...        12.514    03       1
7664      7664   9027  (주)원익테라세미콘  ...        14.443    03       0
8492      8492   9955  (주)이엔코퍼레이션  ...        36.984    10       1
10018    10018  11847     (주)케이엔엔  ...         7.971    10       1
10975    10975  12905  (주)텔콘알에프제약  ...       185.066    03       1
16136    16136  19032     성보화학(주)  ...        24.928    03       1

[7 rows x 169 columns]

In [ ]:
df[~df['상장폐지일'].isnull()]['상장폐지일'].str[0:4]

42       2010
43       2010
44       2010
280      2011
281      2011
         ...
24892    2015
24893    2015
24894    2015
24895    2015
24896    2015
Name: 상장폐지일, Length: 2069, dtype: object

In [ ]:
 a = df.groupby(['거래소코드'])['회계년도'].max().reset_index()
 b= df.loc[~df['상장폐지일'].isnull() , ['거래소코드','상장폐지일']]

 pd.merge(a,b,how='inner',on='거래소코드')

       거래소코드     회계년도       상장폐지일
0        420  2013/12  2015/02/24
1        420  2013/12  2015/02/24
2        420  2013/12  2015/02/24
3        420  2013/12  2015/02/24
4        420  2013/12  2015/02/24
...      ...      ...         ...
2064  271780  2019/12  2020/11/05
2065  271780  2019/12  2020/11/05
2066  311840  2018/12  2020/02/27
2067  950030  2011/03  2011/11/05
2068  950030  2011/03  2011/11/05

[2069 rows x 3 columns]

In [ ]:
df[df['NaN_cnt'] == 16]

               회사명   거래소코드     회계년도  ... EV/EBITDA(배)  산업대분류 NaN_cnt
20814  엘브이엠씨홀딩스(주)  900140  2010/12  ...          NaN     07      16
20815  엘브이엠씨홀딩스(주)  900140  2011/12  ...          NaN     07      16

[2 rows x 167 columns]

In [ ]:
df = df[df['NaN_cnt'] < 16]
df['NaN_cnt'].value_counts()

1    18640
0     2060
Name: NaN_cnt, dtype: int64

In [ ]:
# 산업대분류별로 이상치 탐지,
# 컬럼별로 (3QR - 1QR) * 1.5 인 경우 그 회사의 그 컬럼의 앞 회계년도 값 평균으로 대체

In [ ]:
df['회계년도'] = df['회계년도'].str[0:4].astype(int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df.sort_values(by=['회사명', '회계년도'], ascending=[True, True], inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df_03 = df[df['산업대분류'] == '03']
df_07 = df[df['산업대분류'] == '07']
df_10 = df[df['산업대분류'] == '10']

In [ ]:
df_07.describe()

               거래소코드         회계년도  ...  EV/EBITDA(배)      NaN_cnt
count    2104.000000  2104.000000  ...   2104.000000  2104.000000
mean    53615.104563  2013.522814  ...     32.547056     0.890684
std     82416.655547     4.078574  ...    187.716945     0.312109
min        50.000000  2007.000000  ...      0.000000     0.000000
25%     12700.000000  2010.000000  ...      0.000000     1.000000
50%     37710.000000  2014.000000  ...      9.547500     1.000000
75%     65650.000000  2017.000000  ...     22.277000     1.000000
max    950170.000000  2020.000000  ...   6579.308000     1.000000

[8 rows x 161 columns]

# outlier

## v1. 컬럼별 이상치 값들을 전, 후 회계년도 값으로 대체

In [ ]:
def outlier_replace_nan(df):
  col_list = df.drop(['회사명', '거래소코드', '회계년도', '산업코드', '소속코드', '상장일', '상장폐지일', '감사의견코드', '산업대분류'], axis=1).columns
  for each_col in tqdm(col_list):
    Q1 = np.quantile(df[each_col], 0.25)
    Q3 = np.quantile(df[each_col],0.75)

    minimum = Q1 - 1.5 * (Q3-Q1)
    maximum = Q3 + 1.5 * (Q3-Q1)

    # 각 컬럼별 이상치 값들을 다 결측치로 처리
    df.loc[(df[each_col] < minimum) | (df[each_col] > maximum), each_col] = np.nan
    return df

def outlier_fillna(df):
  code_list = df['거래소코드'].unique().tolist()

  list_of_df = [] 
  for each_code in code_list:
    tmp = df[df['거래소코드'] == each_code]
    tmp.fillna(method='ffill', inplace=True)
    tmp.fillna(method='bfill', inplace=True)
    list_of_df.append(tmp)

  new_df = pd.concat(list_of_df)

  return new_df

df_07_v1 = outlier_fillna(outlier_replace_nan(df_07))

  0%|          | 0/158 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
  0%|          | 0/158 [00:00<?, ?it/s]
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame


## v2. 극단치를 제거

In [ ]:
def outlier_replace_nan_v2(df):
  col_list = df.drop(['회사명', '거래소코드', '회계년도', '산업코드', '소속코드', '상장일', '상장폐지일', '감사의견코드', '산업대분류'], axis=1).columns
  for each_col in tqdm(col_list):
    Q_975 = np.quantile(df[each_col], 0.975)
    Q_025 = np.quantile(df[each_col],0.025)

    df.loc[( Q_025 > df[each_col]) | (df[each_col] > Q_975), each_col] = np.nan

  return df

df_07_after = outlier_replace_nan_v2(df_07)
df_07['NaN_cnt'] = df_07.isnull().sum(1)

  0%|          | 0/158 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
 53%|█████▎    | 84/158 [00:00<00:00, 829.11it/s]/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
100%|██████████| 158/158 [00:00<00:00, 834.62it/s]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

In [ ]:
df_07['NaN_cnt']

28       10
29        6
30        2
31        1
32        5
         ..
25102     8
25103     8
25104    10
25105     9
25106    10
Name: NaN_cnt, Length: 2104, dtype: int64